name: Fancy Cadaver
tagline: Writing and musings by Dylan Reed
#description: put a good description here
markdown: kramdown

url:          http://fancycadaver.com
version:      1.1.1
author:
  name:       'Dylan Reed'
  email:      'dylan@dylanreed.com'
  twitter:    '@dylanreed'
  homepage:   'dylanreed.com'
permalink: /:year/:month/:day/:title/
paginate:     10
gravatar_hash: 36aff981378cc0b408b7d1bc2f082741
gems: [jekyll-paginate]
