name: Fancy Cadaver
tagline: A serial story experiment by Dylan Reed
#description: put a good description here
markdown: redcarpet
pygments: true
url:          http://fancycadaver.com
version:      1.1.1
author:
  name:       'Dylan Reed'
  email:      'dylan@dylanreed.com'
  twitter:    '@dylanreed'
  homepage:   'dylanreed.com'
permalink:    pretty
pygments:     true
paginate:     5
#gravatar_hash: 36aff981378cc0b408b7d1bc2f082741
