
publishDir: "public"
disablePathToLower: true
languageCode: en-us
title: "Dylan's blog"
theme: "hyde-hyde"
canonifyURLs: true
enableRobotsTXT: true
paginate:  4

Menus:
  main:
    - Name: "Books"
      URL: "https://dylanreed.com"

params:

  description: "Writing and musings by Dylan Reed"
  social:
    twitter: dylanreed
    gravatar: "dylan@dylanreed.com"
    instagram: dylanreed
    github: dylanreed